name: Environment

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Print Variable
              run: echo "${{ secrets.TOKEN_SECRECT }}"

            - name: setup
              #run: apt-get update -y
              uses: actions/setup-node@v4
              with:
                node-version: '18'

